# Generated by Django 4.2 on 2023-04-05 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Cabinets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=3)),
                ('frame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.frame')),
            ],
        ),
        migrations.CreateModel(
            name='Aplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('1', 'Отсутствует интернет'), ('2', 'Переферия'), ('3', 'Архитектура ПК'), ('4', 'Программное обеспечение'), ('5', 'Отсутствует интернет'), ('6', 'другое...')], max_length=6)),
                ('comment', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cabinets')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
